protected/models/Eventoadv.php
<?php

/**
 * This is the model class for table "eventoadv".
 *
 * The followings are the available columns in table 'eventoadv':
 * @property integer $id
 * @property string $historia
 * @property integer $edad
 * @property string $fechareporte
 * @property string $fechaocurrencia
 * @property string $hora
 * @property integer $iddependencia
 * @property integer $idreportante
 * @property integer $idlugaro
 * @property integer $idtipoevento
 * @property integer $idincidente
 * @property integer $idtipoeventoadv
 * @property integer $idtransferido
 * @property integer $idfactoresmedioambiente
 * @property integer $idfactoresadmon
 * @property integer $idfactoresrh
 * @property integer $idfactorestec
 * @property integer $idfactortarea
 * @property integer $idfactorespaciente
 * @property integer $gestionado
 * @property string $observaciones
 * @property integer $idclasificacion
 *
 * The followings are the available model relations:
 * @property Dependencia $iddependencia0
 * @property Factoresrh $idfactoresrh0
 * @property Factorestec $idfactorestec0
 * @property Factorestarea $idfactortarea0
 * @property Factorespaciente $idfactorespaciente0
 * @property Gestionado $gestionado0
 * @property Clasificacion $idclasificacion0
 * @property Tiporeportante $idreportante0
 * @property Lugaro $idlugaro0
 * @property Tipoevento $idtipoevento0
 * @property Incidente $idincidente0
 * @property Tipoeventoadv $idtipoeventoadv0
 * @property Transferido $idtransferido0
 * @property Factoresmedioambiente $idfactoresmedioambiente0
 * @property Factorestramitesadmon $idfactoresadmon0
 * @property Otros[] $otroses
 * @property Otrostmp[] $otrostmps
 */
class Eventoadv extends CActiveRecord
{

	public $idincidente = 0;
	public $idtipoeventoadv = 0;	
	public $idfactoresmedioambiente = 0;
	public $idfactoresadmon = 0;
	public $idfactoresrh = 0;
	public $idfactorestec = 0;
	public $idfactortarea = 0;
	public $idfactorespaciente = 0;
	public $gestionado = 2;
	public $idclasificacion = 0;

	public $dependencia_search;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'eventoadv';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('historia, edad, fechareporte, fechaocurrencia, hora, iddependencia, idreportante, idlugaro, idtipoevento, idincidente, idtipoeventoadv, idtransferido, idfactoresmedioambiente, idfactoresadmon, idfactoresrh, idfactorestec, idfactortarea, idfactorespaciente, gestionado, observaciones, idclasificacion, ideventoadvtmp', 'required'),
			array('edad, iddependencia, idreportante, idlugaro, idtipoevento, idincidente, idtipoeventoadv, idtransferido, idfactoresmedioambiente, idfactoresadmon, idfactoresrh, idfactorestec, idfactortarea, idfactorespaciente, gestionado, idclasificacion', 'numerical', 'integerOnly'=>true),
			array('historia', 'length', 'max'=>15),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, historia, edad, fechareporte, fechaocurrencia, hora, iddependencia, idreportante, idlugaro, idtipoevento, idincidente, idtipoeventoadv, idtransferido, idfactoresmedioambiente, idfactoresadmon, idfactoresrh, idfactorestec, idfactortarea, idfactorespaciente, gestionado, observaciones, idclasificacion, dependencia_search', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'edad0' => array(self::BELONGS_TO, 'Edad', 'edad'),
			'iddependencia0' => array(self::BELONGS_TO, 'Dependencia', 'iddependencia'),
			'idfactoresrh0' => array(self::BELONGS_TO, 'Factoresrh', 'idfactoresrh'),
			'idfactorestec0' => array(self::BELONGS_TO, 'Factorestec', 'idfactorestec'),
			'idfactortarea0' => array(self::BELONGS_TO, 'Factorestarea', 'idfactortarea'),
			'idfactorespaciente0' => array(self::BELONGS_TO, 'Factorespaciente', 'idfactorespaciente'),
			'gestionado0' => array(self::BELONGS_TO, 'Gestionado', 'gestionado'),
			'idclasificacion0' => array(self::BELONGS_TO, 'Clasificacion', 'idclasificacion'),
			'idreportante0' => array(self::BELONGS_TO, 'Tiporeportante', 'idreportante'),
			'idlugaro0' => array(self::BELONGS_TO, 'Lugaro', 'idlugaro'),
			'idtipoevento0' => array(self::BELONGS_TO, 'Tipoevento', 'idtipoevento'),
			'idincidente0' => array(self::BELONGS_TO, 'Incidente', 'idincidente'),
			'idtipoeventoadv0' => array(self::BELONGS_TO, 'Tipoeventoadv', 'idtipoeventoadv'),
			'idtransferido0' => array(self::BELONGS_TO, 'Transferido', 'idtransferido'),
			'idfactoresmedioambiente0' => array(self::BELONGS_TO, 'Factoresmedioambiente', 'idfactoresmedioambiente'),
			'idfactoresadmon0' => array(self::BELONGS_TO, 'Factorestramitesadmon', 'idfactoresadmon'),
			'ideventoadvtmp0' => array(self::BELONGS_TO, 'Eventoadvtmp', 'ideventoadvtmp'),

			'otroses' => array(self::HAS_MANY, 'Otros', 'id_eventoadv'),
			'otrostmps' => array(self::HAS_MANY, 'Otrostmp', 'id_eventoadv'),

		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'historia' => 'Numero de Cédula',
			'edad' => 'Edad',
			'fechareporte' => 'Fecha de Reporte',
			'fechaocurrencia' => 'Fecha de Ocurrencia',
			'hora' => 'Hora de Ocurrencia',
			'iddependencia' => 'Dependencia',
			'idreportante' => 'Reportante',
			'idlugaro' => 'Lugar',
			'idtipoevento' => 'Tipo de Evento',
			'idincidente' => 'Incidente',
			'idtipoeventoadv' => 'Tipo de Evento Adverso',
			'idtransferido' => 'Idtransferido',
			'idfactoresmedioambiente' => 'Factores Medio Ambiente',
			'idfactoresadmon' => 'Factores Administrativos',
			'idfactoresrh' => 'Factores de Recurso Humano',
			'idfactorestec' => 'Factores Tecnología',
			'idfactortarea' => 'Factores Tarea',
			'idfactorespaciente' => 'Factores del Paciente',
			'gestionado' => 'Gestionado',
			'observaciones' => 'Descripción del Caso',
			'idclasificacion' => 'Clasificación del Evento Prevenible',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('historia',$this->historia,true);
		$criteria->compare('edad',$this->edad);
		$criteria->compare('fechareporte',$this->fechareporte,true);
		$criteria->compare('fechaocurrencia',$this->fechaocurrencia,true);
		$criteria->compare('hora',$this->hora,true);
		$criteria->compare('iddependencia',$this->iddependencia);
		$criteria->compare('idreportante',$this->idreportante);
		$criteria->compare('idlugaro',$this->idlugaro);
		$criteria->compare('idtipoevento',$this->idtipoevento);
		$criteria->compare('idincidente',$this->idincidente);
		$criteria->compare('idtipoeventoadv',$this->idtipoeventoadv);
		$criteria->compare('idtransferido',$this->idtransferido);
		$criteria->compare('idfactoresmedioambiente',$this->idfactoresmedioambiente);
		$criteria->compare('idfactoresadmon',$this->idfactoresadmon);
		$criteria->compare('idfactoresrh',$this->idfactoresrh);
		$criteria->compare('idfactorestec',$this->idfactorestec);
		$criteria->compare('idfactortarea',$this->idfactortarea);
		$criteria->compare('idfactorespaciente',$this->idfactorespaciente);
		$criteria->compare('gestionado',$this->gestionado);
		$criteria->compare('observaciones',$this->observaciones,true);
		$criteria->compare('idclasificacion',$this->idclasificacion);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	public function search2()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;
		$criteria->with = array( 'iddependencia0' );

		$criteria->compare('id',$this->id);
		$criteria->compare('historia',$this->historia,true);
		$criteria->compare('edad',$this->edad);
		$criteria->compare('fechareporte',$this->fechareporte,true);
		$criteria->compare('fechaocurrencia',$this->fechaocurrencia,true);

		$criteria->compare( 'iddependencia0.dependencia', $this->dependencia_search, true );


		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'sort'=>array(
		        'attributes'=>array(
		            'dependencia_search'=>array(
		                'asc'=>'iddependencia0.dependencia',
		                'desc'=>'iddependencia0.dependencia DESC',
		            ),
		            '*',
		        ),
		    ),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Eventoadv the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/EventoadvController.php
<?php

class EventoadvController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
	return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
	return array(
	array('allow', // allow authenticated user to perform 'create' and 'update' actions
		'actions'=>array('create', 'admin', 'view'),
		'users'=>array('@'),
		),
	array('deny',  // deny all users
		'users'=>array('*'),
		),
	);
}


/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
	$model = $this->loadModel($id);
	$modelOtros = $this->loadModelOtros($id);

	$modelTmp = $this->loadModelTmp($model->ideventoadvtmp);
	$modelOtrosTmp = $this->loadModelOtrosTmp($model->ideventoadvtmp);

	$this->render('view',array(
		'model'=>$model,
		'modelOtros'=>$modelOtros,
		'modelTmp'=>$modelTmp,
		'modelOtrosTmp'=>$modelOtrosTmp
		));
}

/**
* $id es la llave primaria de eventoadvtmp!
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate($id)
{
	$model=new Eventoadv;
	$modeltTmp=$this->loadModelTmp($id);
	$model->attributes = $modeltTmp->getAttributes();

	$modelOtros=new Otros;
	$modelOtrosTmp = $this->loadModelOtrosTmp($id);
	$modelOtros->attributes = $modelOtrosTmp->getAttributes();

	if(isset($_POST['Eventoadv']))
	{
		$model->attributes=$_POST['Eventoadv'];
		$model->ideventoadvtmp = $modeltTmp->id;
		$modelOtros->attributes=$_POST['Otros'];

		$transaction = Yii::app()->db->beginTransaction();
		try 
		{
			if(!$model->save())
				throw new Exception('Error al guardar el evento');

			$modelOtros->id_eventoadv = (int)$model->id;
			if(!$modelOtros->save())
				throw new Exception('Error al guardar el evento(otros)');

			/*$modeltTmp->estadot=1;
			if($modeltTmp->save())
				throw new Exception('Error al guardar el evento(cambiar estado al original)');
				*/
			$command = Yii::app()->db->createCommand();
			$command->update('eventoadvtmp', array(
			    'estadot'=>1,
			), 'id=:id', array(':id'=>$id));

			$transaction->commit();
			Yii::app()->user->setFlash('success', "Evento Creado Correctamente");
			$this->redirect(array('site/index'));
		}
		catch (Exception $e)
		{
			$transaction->rollBack();
			Yii::app()->user->setFlash('danger', "{$e->getMessage()}");
			//$this->refresh();
		} 
	}

	$this->render('create',array(
		'model'=>$model,
		'modelOtros'=>$modelOtros
		));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
	$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

	if(isset($_POST['Eventoadv']))
	{
		$model->attributes=$_POST['Eventoadv'];
		if($model->save())
			$this->redirect(array('view','id'=>$model->id));
	}

	$this->render('update',array(
		'model'=>$model,
		));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
	if(Yii::app()->request->isPostRequest)
	{
// we only allow deletion via POST request
		$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}
	else
		throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
	$dataProvider=new CActiveDataProvider('Eventoadv');
	$this->render('index',array(
		'dataProvider'=>$dataProvider,
		));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
	$model=new Eventoadv('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Eventoadv']))
	$model->attributes=$_GET['Eventoadv'];

$this->render('admin',array(
	'model'=>$model,
	));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
	$model=Eventoadv::model()->findByPk($id);
	if($model===null)
		throw new CHttpException(404,'The requested page does not exist.');
	return $model;
}

public function loadModelTmp($id)
{
	$model=Eventoadvtmp::model()->findByPk($id);
	if($model===null)
		throw new CHttpException(404,'The requested page does not exist.');
	return $model;
}

public function loadModelOtros($id)
{
	$model=Otros::model()->findByAttributes(array('id_eventoadv' => $id));
	if($model===null)
		throw new CHttpException(404,'The requested page does not exist.');
	return $model;
}

public function loadModelOtrosTmp($id)
{
	$model=Otrostmp::model()->findByAttributes(array('id_eventoadv' => $id));
	if($model===null)
		throw new CHttpException(404,'The requested page does not exist.');
	return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
	if(isset($_POST['ajax']) && $_POST['ajax']==='eventoadv-form')
	{
		echo CActiveForm::validate($model);
		Yii::app()->end();
	}
}
}

protected/views/eventoadv/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'historia',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>15)))); ?>

		<?php echo $form->textFieldGroup($model,'edad',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'fechareporte',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->datePickerGroup($model,'fechaocurrencia',array('widgetOptions'=>array('options'=>array(),'htmlOptions'=>array('class'=>'span5')), 'prepend'=>'<i class="glyphicon glyphicon-calendar"></i>', 'append'=>'Click on Month/Year to select a different Month/Year.')); ?>

		<?php echo $form->textFieldGroup($model,'hora',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'iddependencia',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idreportante',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idlugaro',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idtipoevento',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idincidente',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idtipoeventoadv',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idtransferido',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idfactoresmedioambiente',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idfactoresadmon',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idfactoresrh',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idfactorestec',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idfactortarea',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'idfactorespaciente',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'gestionado',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textAreaGroup($model,'observaciones', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

		<?php echo $form->textFieldGroup($model,'idclasificacion',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/eventoadv/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('historia')); ?>:</b>
	<?php echo CHtml::encode($data->historia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('edad')); ?>:</b>
	<?php echo CHtml::encode($data->edad); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fechareporte')); ?>:</b>
	<?php echo CHtml::encode($data->fechareporte); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fechaocurrencia')); ?>:</b>
	<?php echo CHtml::encode($data->fechaocurrencia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hora')); ?>:</b>
	<?php echo CHtml::encode($data->hora); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('iddependencia')); ?>:</b>
	<?php echo CHtml::encode($data->iddependencia); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('idreportante')); ?>:</b>
	<?php echo CHtml::encode($data->idreportante); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idlugaro')); ?>:</b>
	<?php echo CHtml::encode($data->idlugaro); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idtipoevento')); ?>:</b>
	<?php echo CHtml::encode($data->idtipoevento); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idincidente')); ?>:</b>
	<?php echo CHtml::encode($data->idincidente); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idtipoeventoadv')); ?>:</b>
	<?php echo CHtml::encode($data->idtipoeventoadv); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idtransferido')); ?>:</b>
	<?php echo CHtml::encode($data->idtransferido); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idfactoresmedioambiente')); ?>:</b>
	<?php echo CHtml::encode($data->idfactoresmedioambiente); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idfactoresadmon')); ?>:</b>
	<?php echo CHtml::encode($data->idfactoresadmon); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idfactoresrh')); ?>:</b>
	<?php echo CHtml::encode($data->idfactoresrh); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idfactorestec')); ?>:</b>
	<?php echo CHtml::encode($data->idfactorestec); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idfactortarea')); ?>:</b>
	<?php echo CHtml::encode($data->idfactortarea); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idfactorespaciente')); ?>:</b>
	<?php echo CHtml::encode($data->idfactorespaciente); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('gestionado')); ?>:</b>
	<?php echo CHtml::encode($data->gestionado); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('observaciones')); ?>:</b>
	<?php echo CHtml::encode($data->observaciones); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idclasificacion')); ?>:</b>
	<?php echo CHtml::encode($data->idclasificacion); ?>
	<br />

	*/ ?>

</div>

protected/views/eventoadv/admin.php
<h2>Listado de eventos validados</h2>
<?php $this->widget('booster.widgets.TbExtendedGridView',array(
'id'=>'eventoadvtmp-grid',
'dataProvider'=>$model->search2(),
'filter'=>$model,
'responsiveTable' => true,
'columns'=>array(
		array('name' => 'id', 'header' => 'Id Evento Adverso'),
		array('name' => 'historia', 'header' => 'Numero de Cédula'),
		array('name' => 'dependencia_search', 'value'=>'$data->iddependencia0 ? $data->iddependencia0->dependencia : ""', 'header' => 'Dependencia'),
		array('name' => 'fechareporte', 'header' => 'Fecha Reporte'),
		array('name' => 'fechaocurrencia', 'header' => 'Fecha Ocurrencia'),
		array(
			'class'=>'booster.widgets.TbButtonColumn',
			'header' => 'Ver',
			'template'=>'{view}',
			'buttons'=>array(	
				'view' => array
                (
                    'url'=>'Yii::app()->createUrl("eventoadv/view", array("id"=>$data->id))',
                    'options'=>array(
                        'class'=>'btn btn-sm btn-info',
                        'title'=>'Ver',
                    ),
                ),
			)
		),
	),
)); ?>

protected/views/eventoadv/create.php
<h1>Registro de Eventos Adversos Hospital Universitario del Valle</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'modelOtros'=>$modelOtros)); ?>

protected/views/eventoadv/index.php
<?php
$this->breadcrumbs=array(
	'Eventoadvs',
);

$this->menu=array(
array('label'=>'Create Eventoadv','url'=>array('create')),
array('label'=>'Manage Eventoadv','url'=>array('admin')),
);
?>

<h1>Eventoadvs</h1>

<?php $this->widget('booster.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/eventoadv/update.php
<?php
$this->breadcrumbs=array(
	'Eventoadvs'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Eventoadv','url'=>array('index')),
	array('label'=>'Create Eventoadv','url'=>array('create')),
	array('label'=>'View Eventoadv','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Eventoadv','url'=>array('admin')),
	);
	?>

	<h1>Update Eventoadv <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>